---
apiVersion: v1
kind: Namespace
metadata:
  name: qr-code
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qr-code-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: qr-code
  template:
    metadata:
      labels:
        app.kubernetes.io/name: qr-code
    spec:
      containers:
        - name: qr-code-container
          image: 146445828406.dkr.ecr.us-east-1.amazonaws.com/cc:qrcode-vertx3
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 200m
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: qr-code-autoscaling
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: qr-code-deployment
  minReplicas: 5
  maxReplicas: 21
  targetCPUUtilizationPercentage: 70
